inherit_from:
  - '.rubocop-rails.yml'

require:
  - rubocop-rails
  

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.3
  TargetRailsVersion: 7.0.4
  Exclude:
    - 'bin/**/*'
    - '**/db/migrate/*'
    - 'config/**/*'
    - 'lib/tasks/auto_annotate_models.rake'  
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'old/**/*'
    - 'test/**/*'
    - 'vendor/**/*'    
    - 'tmp/**/*'
    - '**/spec_helper.rb'        
    - '**/Gemfile.lock'
    - '**/vendor/**/*'
    - '**/Rakefile'
    - '**/rails'